// src/app/mock-data/mock-tourist-places.ts

import { TouristPlace } from '../Model/travel.models';

export const mockTouristPlaces: TouristPlace[] = [
  {
    id: 'fr1_id',
    placeId: 'eiffel_tower',
    countryId: 'fr',
    name: 'Eiffel Tower',
    description: 'Iconic iron lattice tower on the Champ de Mars in Paris.',
    imageUrl: '/assets/tourbook9.webp',
    cost: 125,
    rating: 4.7,
    highlights: [
      'Skip-the-line access',
      'Panoramic city views',
      'Restaurant dining',
    ],
    bestTimeToVisit: 'Sunset',
    duration: '2-3 hours',
    accommodation: {
      hotelName: 'Hotel Paris View',
      roomType: 'Deluxe Suite',
      checkInDate: '2025-06-01',
      checkOutDate: '2025-06-03',
      numberOfRooms: 1,
      occupancyDetails: '2 adults',
      specialRequests: 'Eiffel Tower view room',
    },
    travelDetails: {
      transportationMode: 'Metro',
      travelDuration: '20 minutes',
      cost: 10,
    },
  },
  {
    id: 'eg1_id',
    placeId: 'pyramids_giza',
    countryId: 'fr',
    name: 'Pyramids of Giza',
    description: 'Ancient pyramids located just outside Cairo.',
    imageUrl: '/assets/tourbook10.webp',
    cost: 80,
    rating: 4.9,
    highlights: ['Camel rides', 'Light and sound show', 'Guided tours'],
    bestTimeToVisit: 'Early morning',
    duration: '4-5 hours',
    accommodation: {
      hotelName: 'Giza View Hotel',
      roomType: 'Suite',
      checkInDate: '2025-06-10',
      checkOutDate: '2025-06-12',
      numberOfRooms: 1,
      occupancyDetails: '2 adults, 1 child',
      specialRequests: 'Pyramid view room',
    },
    travelDetails: {
      transportationMode: 'Taxi',
      travelDuration: '30 minutes',
      cost: 20,
    },
  },
  {
    id: 'us1_id',
    placeId: 'grand_canyon',
    countryId: 'fr',
    name: 'Grand Canyon',
    description:
      'Famous canyon in Arizona known for its immense size and colorful landscape.',
    imageUrl: '/assets/tourbook11.webp',
    cost: 150,
    rating: 4.8,
    highlights: ['Hiking trails', 'Guided tours', 'Helicopter rides'],
    bestTimeToVisit: 'Spring',
    duration: '1-2 days',
    accommodation: {
      hotelName: 'Canyon Lodge',
      roomType: 'Standard Room',
      checkInDate: '2025-07-01',
      checkOutDate: '2025-07-03',
      numberOfRooms: 1,
      occupancyDetails: '2 adults',
      specialRequests: 'Canyon view room',
    },
    travelDetails: {
      transportationMode: 'Car Rental',
      travelDuration: '5 hours',
      cost: 50,
    },
  },
  {
    id: 'it1_id',
    placeId: 'colosseum',
    countryId: 'fr',
    name: 'Colosseum',
    description: 'Ancient Roman gladiatorial arena located in Rome.',
    imageUrl: '/assets/tourbook12.webp',
    cost: 100,
    rating: 4.6,
    highlights: ['Guided tours', 'Special exhibitions', 'Underground tours'],
    bestTimeToVisit: 'Spring',
    duration: '2-3 hours',
    accommodation: {
      hotelName: 'Rome City Hotel',
      roomType: 'Double Room',
      checkInDate: '2025-05-20',
      checkOutDate: '2025-05-23',
      numberOfRooms: 1,
      occupancyDetails: '2 adults',
      specialRequests: 'Colosseum view room',
    },
    travelDetails: {
      transportationMode: 'Bus',
      travelDuration: '15 minutes',
      cost: 5,
    },
  },
  {
    id: 'jp1_id',
    placeId: 'mt_fuji',
    countryId: 'fr',
    name: 'Mount Fuji',
    description: 'Japan’s highest mountain and an active stratovolcano.',
    imageUrl: '/assets/tourbook13.webp',
    cost: 75,
    rating: 4.9,
    highlights: ['Hiking', 'Photography', 'Traditional inns'],
    bestTimeToVisit: 'Summer',
    duration: '1-2 days',
    accommodation: {
      hotelName: 'Fuji View Inn',
      roomType: 'Traditional Room',
      checkInDate: '2025-08-01',
      checkOutDate: '2025-08-03',
      numberOfRooms: 1,
      occupancyDetails: '2 adults',
      specialRequests: 'Mountain view room',
    },
    travelDetails: {
      transportationMode: 'Train',
      travelDuration: '2 hours',
      cost: 30,
    },
  },
  {
    id: 'br1_id',
    placeId: 'cristo_redentor',
    countryId: 'fr',
    name: 'Christ the Redeemer',
    description: 'Giant statue of Jesus Christ in Rio de Janeiro, Brazil.',
    imageUrl: '/assets/tourbook14.webp',
    cost: 90,
    rating: 4.5,
    highlights: ['Panoramic views', 'Guided tours', 'Photography'],
    bestTimeToVisit: 'Sunrise',
    duration: '1-2 hours',
    accommodation: {
      hotelName: 'Rio View Hotel',
      roomType: 'Deluxe Room',
      checkInDate: '2025-09-10',
      checkOutDate: '2025-09-12',
      numberOfRooms: 1,
      occupancyDetails: '2 adults',
      specialRequests: 'Christ the Redeemer view room',
    },
    travelDetails: {
      transportationMode: 'Cable Car',
      travelDuration: '10 minutes',
      cost: 15,
    },
  },
  {
    id: 'cn1_id',
    placeId: 'great_wall',
    countryId: 'fr',
    name: 'Great Wall of China',
    description:
      'Ancient series of walls and fortifications located in northern China.',
    imageUrl: '/assets/tourbook15.webp',
    cost: 120,
    rating: 4.7,
    highlights: ['Hiking', 'Historical tours', 'Photography'],
    bestTimeToVisit: 'Spring',
    duration: '3-4 hours',
    accommodation: {
      hotelName: 'Great Wall Hotel',
      roomType: 'Suite',
      checkInDate: '2025-10-01',
      checkOutDate: '2025-10-03',
      numberOfRooms: 1,
      occupancyDetails: '2 adults',
      specialRequests: 'Great Wall view room',
    },
    travelDetails: {
      transportationMode: 'Bus',
      travelDuration: '1.5 hours',
      cost: 25,
    },
  },
  {
    id: 'au1_id',
    placeId: 'sydney_opera_house',
    countryId: 'fr',
    name: 'Sydney Opera House',
    description: 'Famous performing arts center located in Sydney Harbour.',
    imageUrl: '/assets/tourbook16.webp',
    cost: 130,
    rating: 4.8,
    highlights: ['Opera performances', 'Guided tours', 'Photography'],
    bestTimeToVisit: 'Evening',
    duration: '2-3 hours',
    accommodation: {
      hotelName: 'Sydney Harbour Hotel',
      roomType: 'Deluxe Room',
      checkInDate: '2025-12-01',
      checkOutDate: '2025-12-03',
      numberOfRooms: 1,
      occupancyDetails: '2 adults',
      specialRequests: 'Opera House view room',
    },
    travelDetails: {
      transportationMode: 'Ferry',
      travelDuration: '30 minutes',
      cost: 20,
    },
  },
];
