import { TouristPlace } from 'src/app/Model/travel.models';

export const mockTouristPlaces: TouristPlace[] = [
  {
    id: 'fr1',
    countryId: 'fr',
    name: 'Eiffel Tower',
    description: 'Iconic iron lattice tower on the Champ de Mars in Paris.',
    imageUrl: '/assets/tourbook9.webp',
    cost: 125,
    rating: 4.7,
    highlights: [
      'Skip-the-line access',
      'Panoramic city views',
      'Restaurant dining',
    ],
    bestTimeToVisit: 'Sunset',
    duration: '2-3 hours',
  },
  {
    id: 'fr2',
    countryId: 'fr',
    name: 'Louvre Museum',
    description:
      'World-famous museum housing iconic works like the Mona Lisa and Venus de Milo.',
    imageUrl: '/assets/tourbook13.webp',
    cost: 100,
    rating: 4.8,
    highlights: [
      'Art masterpieces',
      'Skip-the-line access',
      'Audio-guided tours',
    ],
    bestTimeToVisit: 'Morning',
    duration: '3-4 hours',
  },
  {
    id: 'fr3',
    countryId: 'fr',
    name: 'Palace of Versailles',
    description:
      'Lavish palace showcasing French opulence with stunning gardens.',
    imageUrl: '/assets/tourbook14.webp',
    cost: 120,
    rating: 4.6,
    highlights: ['Palace tours', 'Fountain shows', 'Beautiful gardens'],
    bestTimeToVisit: 'Spring',
    duration: '4-5 hours',
  },
  {
    id: 'br1',
    countryId: 'br',
    name: 'Christ the Redeemer',
    description:
      'Iconic statue overlooking Rio de Janeiro, offering breathtaking views.',
    imageUrl: '/assets/tourbook1.webp',
    cost: 30,
    rating: 4.9,
    highlights: ['Panoramic views', 'Guided tours', 'Cultural significance'],
    bestTimeToVisit: 'Morning',
    duration: '2-3 hours',
  },
  {
    id: 'br2',
    countryId: 'br',
    name: 'Sugarloaf Mountain',
    description: 'Granite peak with cable car rides and sweeping views of Rio.',
    imageUrl: '/assets/tourbook4.webp',
    cost: 35,
    rating: 4.8,
    highlights: [
      'Cable car rides',
      'City and ocean views',
      'Photography spots',
    ],
    bestTimeToVisit: 'Evening',
    duration: '2-3 hours',
  },
  {
    id: 'br3',
    countryId: 'br',
    name: 'Iguazu Falls',
    description:
      'Majestic waterfalls located on the border between Brazil and Argentina.',
    imageUrl: '/assets/tourbook5.webp',
    cost: 50,
    rating: 4.9,
    highlights: ['Boat tours', 'Hiking trails', 'Nature views'],
    bestTimeToVisit: 'Autumn',
    duration: '3-4 hours',
  },
  {
    id: 'jp1',
    countryId: 'jp',
    name: 'Hillbase Tower',
    description:
      'Modern tower offering panoramic views of the bustling Tokyo skyline.',
    imageUrl: '/assets/tourbook10.webp',
    cost: 50,
    rating: 4.7,
    highlights: [
      'Skip-the-line access',
      'Panoramic city views',
      'Traditional tea ceremony',
    ],
    bestTimeToVisit: 'Evening',
    duration: '2-3 hours',
  },
  {
    id: 'jp2',
    countryId: 'jp',
    name: 'Mount Fuji',
    description:
      'Japan’s tallest peak, a symbol of the nation with hiking and stunning views.',
    imageUrl: '/assets/tourbook6.webp',
    cost: 40,
    rating: 4.9,
    highlights: ['Hiking trails', 'Scenic vistas', 'Photography spots'],
    bestTimeToVisit: 'Autumn',
    duration: '5-6 hours',
  },
  {
    id: 'jp3',
    countryId: 'jp',
    name: 'Arashiyama Bamboo Grove',
    description:
      'Serene bamboo forest offering a peaceful and picturesque atmosphere.',
    imageUrl: '/assets/tourbook7.webp',
    cost: 20,
    rating: 4.8,
    highlights: ['Bamboo forest walks', 'Tranquil atmosphere', 'Photography'],
    bestTimeToVisit: 'Morning',
    duration: '1-2 hours',
  },
];
